### PR TITLE
Update gradle config and minimum sdk

### PR DESCRIPTION
**Pull request by chynl**

### CODE REVIEW

**Review by WideLee — COMMENTED** [review]
I have added the .idea directory into .gitignore

**Review by WideLee — COMMENTED** [review]
What does \<uses-sdk tools:overrideLibrary\> use for? It seems that you add it but remove it finally

**Comment by chynl** [comment]
Your `.gitignore` does not ignore the whole `.idea` directory but only two files within it.

```
# .gitignore
*.iml
.gradle
/local.properties
/.idea/workspace.xml
/.idea/libraries
.DS_Store
/build
/captures
.externalNativeBuild
```

This file is generated automatically by Android Studio so other files in `.idea` will not be ignored.

**Comment by chynl** [comment]
`<uses-sdk tools:overrideLibrary>` needs to be declared at the manifest file of the `samples` module. Otherwise there will be a compilation error:

```
Error:Execution failed for task ':samples:processDebugManifest'.
Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 22 declared in library [sysu.mobile.limk:indoormapview:0.1] C:\Users\Steven Liu\.android\build-cache\1b6920740a001a4624a785850b51581ede6d42d6\output\AndroidManifest.xml
Suggestion: use tools:overrideLibrary="sysu.mobile.limk.library" to force usage
```

I am not sure how this error occurs so I just follow the suggestion at the last line.

**Comment by WideLee** [comment]
It is because the min SDK in library is 22 and it doesn't change in jcenter yet, I'll upload it in a minute. Before the update submit been approved, you can replace the dependencies and use the local library.

```
dependencies {
    // compile 'sysu.mobile.limk:indoormapview:0.1'
    compile project(':indoormapview')
}
```

**Comment by chynl** [comment]
OK, thanks

**Pull request merged**
